### ISSUE TITLE
Ammy fails with Xamarin.Forms

### ISSUE THREAD

**Issue by byme8** [AmmyUI/AmmyUI#104]
I installed latest AmmyUI from nuget to Xamarin.Forms project and it fails on launch with next exception:
![image](https://user-images.githubusercontent.com/5927686/29252985-eedd690e-807a-11e7-98cf-8d2560169ada.png)
[Here](https://github.com/byme8/TestAmmyUI) is repository.

**Comment by byme8** [comment]
I did test for WPF it works as expected

**Comment by ionoy** [comment]
Thanks for the feedback!

What project are you launching? Android or iOS?

**Comment by byme8** [comment]
I tried with UWP

**Comment by ionoy** [comment]
Can you send a simplified project sample? You can delete all the XAML or code files.

**Comment by byme8** [comment]
Here https://github.com/byme8/TestAmmyUI

**Comment by byme8** [comment]
Hm... at Android works as expected.

**Comment by ionoy** [comment]
I have uploaded new NuGet package (1.2.83). Runtime update still doesn't work for UWP, but there is no startup crash.

Unfortunately, seems like some stuff changed in the updated UWP and previous connection strategy doesn't work anymore. It works in [LiveXAML](http://www.livexaml.com), but it won't be easy to backport it since network architecture is shared between all Ammy supported platforms at the moment. Maybe, a bit later I will just copy all the new code from LiveXAML to Ammy, but I can't deal with it now.

**Comment by byme8** [comment]
Thank you!
