### ISSUE TITLE
Support using uri based xmlns

### ISSUE THREAD

**Issue by draco1023** [AmmyUI/AmmyUI#14]
How can I "using" in ammy? Such as xmlns:metro="http://metro.mahapps.com/winfx/xaml/controls"
in XAML

**Comment by ionoy** [comment]
Two ways

1)

    using MahApps.Metro.Controls
 
    MetroWindow "MyApp.MainWindow" {
    }

Note, that you don’t have to use any prefixes, Ammy resolves them automatically. In case you don’t want to import whole namespace or there is an ambiguity between types, you can also use fully qualified name:

2)

    MahApps.Metro.Controls.MetroWindow "MyApp.MainWindow" {
    }


http://www.ammyui.com/documentation/syntax/#using

**Comment by draco1023** [comment]
Yep. I know how to do it in the right way, just wonder if this can be done without knowing actual namespace. Thank you.

**Comment by ionoy** [comment]
Not at the moment, no. We are going to add Resharper-like suggestions in later versions.

**Comment by matkoch** [comment]
@ionoy I guess it's certainly the same issue, but how do I handle a case as such:

```
<ListBox>
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="MouseDoubleClick">
            <i:InvokeCommandAction Command="{Binding YourCommand}"/>
        </i:EventTrigger>
    </i:Interaction.Triggers>
</ListBox>
```

With assembly: `System.Windows.Interactivity.dll`
And namespace: `http://schemas.microsoft.com/expression/2010/interactivity`

How should the ammy look like?

**Comment by ionoy** [comment]
Will try it today and notify you!

**Comment by ionoy** [comment]
`Interaction` defines attached property `Triggers` as a private field, even though official recommendation is making it public. Oh well, at least it's fixed now :)

Blend's `EventTrigger` also causes problems, since it has the same name as WPF's one. You can overcome it by using fully qualified name, like on a screenshot below.

![image](https://cloud.githubusercontent.com/assets/592624/22249514/fb022756-e24b-11e6-843d-741686fe5633.png)

Although you can make you life easier by defining `iEventTrigger` alias in a global scope and using it where ever.

```
using System.Windows.Interactivity

alias iEventTrigger() {
  System.Windows.Interactivity.EventTrigger {  }  
}

Window "Ammy.Test.Workbench.MainWindow" {
  ListView { 
    Interaction.Triggers: [
      @iEventTrigger() {
        InvokeCommandAction { Command: "{Binding YourCommand}" }
      }
    ]
  }
}
```

I've uploaded new version of Ammy to MyGet.

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and update-package Ammy. You might need to restart visual studio, since it uses assemblies from a package.

Thanks!

**Comment by matkoch** [comment]
@ionoy didn't expect such a quick response :) Thanks and keep it up!

I will try this on weekend probably. You know - pet project :)

**Comment by matkoch** [comment]
@ionoy worked :) Thanks again!
