### ISSUE TITLE
Color value indicators

### ISSUE THREAD

**Issue by ionoy** [AmmyUI/AmmyUI#2]
We should parse color values like "#0000FF" and display corresponding color block nearby.

![color-values](https://cloud.githubusercontent.com/assets/592624/21645852/6c1078c2-d29c-11e6-8430-d3248ca4f595.png)

**Comment by Yeah69** [comment]
I like the ReSharper (or even Visual Studio!?) style of this. There a slim underline is used. It is pretty decent and not too eye catchy. Thus, if you search for the color then you know it is there and can find it fast, otherwise it will not distract too much.

![image](https://cloud.githubusercontent.com/assets/11756150/21886510/5446fc68-d8bc-11e6-88d6-8096e67f0032.png)

In my opinion the style in your screenshot is almost too eye-catchy. However, I would still prefer it this way instead of not having this feature at all.

Great idea!

**Comment by ionoy** [comment]
Yeah, I guess Resharper provides same information with less clutter.

**Comment by ionoy** [comment]
Done! Updated extension and Ammy package will be published by the end of the week.
