### ISSUE TITLE
NullReferenceException in VisualStudio editor

### ISSUE THREAD

**Issue by lucamnn** [AmmyUI/AmmyUI#22]
While the editor is working in our test project, when i try to create an ammy file in one of our production project, i'm getting a NullReferenceException as showed in the attached image
![ammy_editor_error](https://cloud.githubusercontent.com/assets/25318752/22240708/8c3d6ea4-e21c-11e6-8fab-59e37da3dac2.png)

**Comment by ionoy** [comment]
This seems like an old version of Ammy. Could you try updating and see if error still appears?

**Comment by lucamnn** [comment]
I'm running version 1.0.15 of VS extension.
The project is referencing the 1.1.15 nuget package.

**Comment by ionoy** [comment]
This is weird. `GetShadowCopyFileList` method is long gone. It's possible, that extension load DLL's from wrong packages directory. Do you have multiple versions of Ammy installed?

**Comment by lucamnn** [comment]
It seems that Visual Studio had not uninstalled Ammy 1.1.3 that still was in the packages folder.
I've deleted the folder, reloaded Visual Studio and now the error message is changed.

![ammy_editor_error 2](https://cloud.githubusercontent.com/assets/25318752/22242502/e0a17678-e223-11e6-9bd5-35b9cdccd258.png)

**Comment by ionoy** [comment]
Extension should've chosen 1.1.15 over 1.1.3, so this is still a bug, so thank you for reporting it.

As for current error, it seems like extension cannot find project associated with `NewControl1.ammy`. Try to close this file, make sure that project is loaded and then open file again by double clicking it in solution explorer.

I have an idea how to fix it, but need to make sure about circumstances. 

Thanks!

**Comment by ionoy** [comment]
I've uploaded new version of Ammy to MyGet. Please check if it fixes you problem.

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and `update-package Ammy`. You might need to restart visual studio, since it uses assemblies from a package.

Thanks!

**Comment by lucamnn** [comment]
Perfect: the new version has resolved the issue.
