### ISSUE TITLE
NoesisGUI Integration

### ISSUE THREAD

**Issue by aienabled** [AmmyUI/AmmyUI#24]
Hi!

Currently I'm working on the integration of Ammy with [NoesisGUI](http://noesisengine.com) and I need a simple API to convert Ammy to XAML before feeding it to NoesisGUI.
I suppose that's not so easy as Ammy need to knew about the .NET Reflection context to properly build XML namespaces, so it's not possible to make a simple console Ammy2Xaml tool which absolutely don't know about the available .NET types in the project.

Please consider making an API method like this:
```C#
void BuildXaml(Stream inputStreamAmmy, Stream outputStreamXaml, Stream outputStreamErrors, DelegateCallbackResolveNamespace сallbackResolveNamespace);

/// <summary>
/// Callback to resolve CLR namespace for XML importing.
/// </summary>
/// <param name="typeName">Type name to resolve (could include namespace prefix).</param>
/// <param name="namespaces">Namespaces defined in the Ammy file usings block.</param>
/// <returns>CLR namespace of the type.</returns>
public delegate string DelegateCallbackResolveNamespace(string typeName, IReadOnlyList<string> namespaces);
```

Please note that method ```Ammy.BuildXaml()``` should call ```сallbackResolveNamespace``` once per type name and the result must be cached during the method invocation (so the cache is created once per input file stream).
Also I would like to have ```outputStreamErrors``` if Ammy could print any parsing/generation errors. If it's not supported and you have no plans regarding implementing any errors reporting you can omit it.

Regards!

**Comment by ionoy** [comment]
Ammy actually needs to build whole type tree before attempting semantic analysis. After first load type tree is cached, so we don't read it anytime some edit happens in VS. We run a special backend, that reads all provided reference assemblies and creates big "type tree". This type tree looks something like this:

```
- System (ns)
  - String (type)
    - ToString (method)
    - Length(property)
  - Math (type)
    ...
```

After that we open few default XAML namespaces, like `System.Windows`, `System.Windows.Controls` etc. Types from these namespaces become available without `using` or fully qualified name. This means, that when Ammy encounters node with name `Window` it can easily bind it to `Window` type since it was already opened. 

Essentially there should be a possibility to load all types at once. What is the source of all your types? I would gladly help you create a backend for NoesisGUI if it would mean you switching to Ammy!

**Comment by aienabled** [comment]
@ionoy, thanks!
> I would gladly help you create a backend for NoesisGUI if it would mean you switching to Ammy!

I'm seriously considering switching our game UI (based on NoesisGUI with XAML) to use Ammy instead of XAML. We already have hundreds of controls and thousands of styles/templates/etc resources, so converting it to Ammy might help to locate issues in Ammy and improve quality.

However, our game is not a simple case of using NoesisGUI. It's heavily modding-inspired and we ship core part of the game (containing all the game content, gameplay code, XAML UI, etc) in open-source form (eventually it will become available on GitHub). All the tools and preprocessors are integrated into the game to compile everything from source (texture/audio loaders, shaders compiler, Roslyn compiler, XAML builder (removed since NoesisGUI 1.3 as it learned to directly and very effectively parse XAML now), etc).
And the game is cross-platform (targets Windows, Mac and Linux), so all these tools should work everywhere as well.

> Essentially there should be a possibility to load all types at once.

Yes, it's possible. But the used types might change (new assembly loaded, previous assembly might be not relevant anymore - our game providers live recompilation when any C# file changes). So there should be an API to reset the Ammy's type tree/cache, or even better - to create a new builder with available types. For example:
```C#
public class AmmyToXamlBuilder
{
    public AmmyToXamlBuilder(Type[] typesToUse) { }

    void BuildXaml(Stream inputStreamAmmy, Stream outputStreamXaml, Stream outputStreamErrors, DelegateCallbackResolveNamespace сallbackResolveNamespace) { ... }

    /// <summary>
    /// Callback to resolve CLR namespace for XML importing.
    /// </summary>
    /// <param name="typeName">Type name to resolve (could include namespace prefix).</param>
    /// <param name="namespaces">Namespaces defined in the Ammy file usings block.</param>
    /// <returns>CLR namespace of the type.</returns>
    public delegate string DelegateCallbackResolveNamespace(string typeName, IReadOnlyList<string> namespaces);
}
```

So this way I will be able to create an instance of ```AmmyToXamlBuilder``` and provide to its constructor the available types (including types from System assemblies) to include into the type tree.

Because NoesisGUI has different types (but 99% compatible with WPF) - and most importantly it's crossplatform - ```AmmyToXamlBuilder``` should be contained in a separate assembly which is free from any Windows/WPF dependencies.

We could ignore binding converters implementation right now (and other code-generation related stuff; I'm right that you're using code generation for that?) and focus just on building XAML from available Ammy files, cross-platform. Do you think that's possible?

Regards!

**Comment by ionoy** [comment]
I'm thinking we would need a backend connection layer, similar to what you propose with `AmmyToXamlBuilder`. Can you provide .NET types to it? Like:

```
interface IAmmyBackend
{
  void RegisterType(Type type);
  void UnregisterType(Type type);
}
```

Ammy will need more stuff from this backend, but it will be clearer during the development.

Also, why do you want to generate XAML by yourself? I think it would be best to leave current generation tactic the same, since it has to be compatible with current Visual Studio extension and build tasks.

As for backend project, I propose we use a https://github.com/ammyui/ammyui repository. There will be two projects: `Ammy.BackendLayer` and `Ammy.NoesisGUIBackend`. Backend will contain all the interfaces that NoesisGUI should implement and Ammy itself will use `BackendLayer` to request necessary data. 

What do you think?

**Comment by ionoy** [comment]
`NoesisGUIBackend` can also be in a separate repository with https://github.com/ammyui/ammyui as a submodule.

**Comment by aienabled** [comment]
>  Can you provide .NET types to it? Like:

Yes, the proposed backend should be fine!


> Also, why do you want to generate XAML by yourself?

Our game build everything from source itself (and it's cross-platform), so it should build all the code (including *.ammy.cs codebehind classes) and then build XAML from Ammy files. That's why we cannot rely on MSBuild build tasks (also the game doesn't use MSBuild at all, only Roslyn compiler), practically our modders could simply use Notepad (but we expect them to use VS Code for cross-platform development) and they expect that the game will provide live-reloading of changed code and assets, including UI.

Regarding the ```NoesisGUIBackend``` - sounds like a good idea. I can implement the required interfaces.

I don't think adding ```Ammy.BackendLayer``` to https://github.com/ammyui/ammyui is a good idea - it contains various non-related stuff. And it will grow over time with even more non-related stuff. So ideally I would like to have ```Ammy.BackendLayer``` as a separate repository, say, ```AmmyIntegration```, and have it as a submodule for ```AmmyNoesisGUIBackend```.

Regards!

**Comment by ionoy** [comment]
You are right about repositories, it's better to separate them. 

If you have your own live-reloading implemented, then `IAmmyBackend` should also have a property like:

```
  IsAmmyLiveReloadEnabled { get; }
```

Which in NoesisGUI case will return `false`, so Visual Studio won't try to send updates.

As for XAML generation there should be a way to both allow Ammy to generate files like with other backends (WPF/UWP etc) and to delegate it to interface implementer. 

My proposal is:

```
  void GenerateFile(string ammyFilename, string outputXaml) 
```
`outputXaml` is string because Ammy already stores it in a string after compilation. If NoesisGUI needs a stream you can convert it inside `GenerateFile`

Do you have some kind of BAML generation tool? At the moment Ammy has an additional compilation step, that compiles XAML to BAML to see if everything resolves properly.

**Comment by aienabled** [comment]
Yes, we have our own live-reloading so it's a good idea to have `IsAmmyLiveReloadEnabled` property in backend.

Regarding the XAML generation - do you mean that the `GenerateFile()` method will be added to `IAmmyBackend` and should be implemented in `AmmyNoesisGUIBackend`? If so, in which cases it will be invoked by Ammy?

BAML - no, NoesisGUI since v1.3 (now in beta) could read XAML directly, and actually do it blazing fast (even faster than already very fast BAML reader in 1.2).

**Comment by ionoy** [comment]
Well, maybe `GenerateFile` is not such a great idea. It would probably be better for a backend to implement:

```
   void CompilationFinished(CompilationResult result);
```

Where CompilationResult would contain all the needed properties, like:

```
class CompilationResult
{
  string ProjectName { get; }
  bool IsSuccess { get; }
  CompilerMessage[] CompilerMessages { get; }
  AmmyFile[] Files { get; }  
}

class AmmyFile
{
  string Filename { get; }
  string Xaml { get; }
}
```

This way, upon receiving CompilationFinished call you would have all the information to proceed.

**Comment by aienabled** [comment]
I see. Please clarify if Ammy will automatically detect the file changes at the specified folder, invoke the compilation and then call the `CompilationFinished()` method to notify the backend to use new files.

**Comment by ionoy** [comment]
Ah, I forgot that you are not bound to Visual Studio/MSBuild. I don't think it's a good idea for Ammy to detect changes by itself, since there will be different environments with different rules. 

How about `RequestCompilation` event then?

Let me understand your development process. What happens if I use VS and hit build? You said that Noesis doesn't use MSBuild tasks, so how does building work? 

VS extension also recompiles project constantly, on every TextBuffer change. In this case we shouldn't bother with `CompilationFinished` call until file is actually saved, right?

**Comment by ionoy** [comment]
Btw, we can move this discussion to Telegram/Skype, since there will be a lot of questions in the beginning. 
TG: +372 58128226
Skype: mihhail.maslakov@gmail.com

**Comment by aienabled** [comment]
Thanks. I will contact you at Skype now :-).

**Comment by Mike-EEE** [comment]
I wanted to send my support for this idea.  It got me checking out Noesis and it looks like it has made some progress.  It actually looks as if it is THE cross-platform Xaml solution available out there in the marketplace now.  Albeit a paid one, but I think at this point that is a necessity, as MSFT [wrestles with the extremely popular request of porting System.Xaml to .NET Core](https://github.com/dotnet/corefx/issues/5766).

In any case, I too would be interested in seeing Ammy support for Noesis and might be interested in testing it out in the future. 👍

**Comment by aienabled** [comment]
Done!
http://www.noesisengine.com/forums/viewtopic.php?f=3&t=1013&p=5547#p5547
Thanks to @ionoy for his great effort for supporting NoesisGUI.

Regards!

**Comment by Mike-EEE** [comment]
Wow!  That was fast @aienabled!  Way 2 go. 🥇
