### ISSUE TITLE
Attached property usage

### ISSUE THREAD

**Issue by jstaro** [AmmyUI/AmmyUI#33]
Are attached properties supposed to work yet, because I'm having trouble with one.
![clipboard image 12](https://cloud.githubusercontent.com/assets/4079934/22342153/a24fdd8e-e3f3-11e6-9e45-a1349baeac48.png)

**Comment by ionoy** [comment]
Yes, attached properties should definitely work. I will check it today!

**Comment by ionoy** [comment]
Found the problem. Attached properties from parsed files are not registered. So it would work if your attached property was defined in a separate assembly, but since it's inside a same project it's not registered.

Anyway, I'm going to fix it soon and notify you!

**Comment by ionoy** [comment]
Alright, it should work now. You can get latest version from MyGet feed.

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and update-package Ammy. You might need to restart visual studio, since it uses assemblies from a package.

Thanks!

**Comment by jstaro** [comment]
Works wonderfully in 1.1.25.
