### ISSUE TITLE
Inline binding converter fails on null check

### ISSUE THREAD

**Issue by chrischu** [AmmyUI/AmmyUI#50]
I have the following property assignment:
`IsEnabled: bind SelectedRule convert (AvailableRuleViewModel item) => item != null`

and the error is:
![image](https://cloud.githubusercontent.com/assets/447251/23097795/4b0b4286-f63e-11e6-9923-b47e8c2d0e17.png)

I also tried changing the binding conversion expression to `(AvailableRuleViewModel item) => item != null ? true : false` but that didn't change anything.

**Comment by ionoy** [comment]
Fixed!

Next NuGet release is planned in a few days, maybe Tuesday or Wednesday. You will actually have to `install-package Ammy.WPF` since Ammy is on multiple platforms now.

If you want, I can upload fixed version today on MyGet. But it's not tested yet, and I can't guarantee that everything works properly.

Thanks for submitting an issue!
