### ISSUE TITLE
Ammy.1.2.11.nupkg 

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#53]
Ammy.1.2.11.nupkg  seems to be not complete. Start new WPF project, add nuget package. Compiler complains about
`public string T = AmmySidekick.RuntimeUpdateHandler.CurrentlyUpdatedTargetId;`
in internal.cs  file.
Seems that AmmySidekick is not present in the package.

**Comment by ionoy** [comment]
Ammy is now multiplatform, so since a week ago, you need to install `Ammy.WPF` package, which has `Ammy` as a dependency. Unfortunately, I don't have a communication channel with people already using Ammy to promote this information. Sorry for that.

Also, I will soon upload a new version to NuGet, since the last one contained a critical bug. I will notify you as soon as I do that.

**Comment by ionoy** [comment]
I've uploaded a new version to NuGet, you can update now. 

Also, make sure you update VS Extension: https://marketplace.visualstudio.com/items?itemName=ionoy.Ammy
For some people, it doesn't show that there is an update in VS. I'm assuming this is due to adding VS2017 support.

**Comment by isukces** [comment]
It works. Thank you.
