### ISSUE TITLE
The using syntax does not work properly

### ISSUE THREAD

**Issue by spowner** [AmmyUI/AmmyUI#6]
I tried to use the MahApps.Metro library with ammy. However, using syntax does not find the MahApps.Metro namespace.
Unusual is that other referenced libraries are references
In my opinion, the difference is that the MahApps.Metro library is a dll that contains a '.' In other words, 'MahApps.Metro.dll', ammy's using syntax does not work in a library containing '.'

![image](https://cloud.githubusercontent.com/assets/5735665/21924007/74424762-d9ba-11e6-9ca7-aa6d4070920d.png)

![image](https://cloud.githubusercontent.com/assets/5735665/21924016/86412104-d9ba-11e6-94a4-030cb24e1c96.png)

**Comment by ionoy** [comment]
Going to investigate it right now. I don't think '.' should matter.

**Comment by ionoy** [comment]
Alright, should be fixed now. Backend had a problem with resolving "System.Windows.Interactivity.dll" assembly. 
I'm going to update official Nuget package in a few days, meanwhile I've uploaded new version to MyGet feed:

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click "Update" button there.

After that just "update-package Ammy". You might need to restart visual studio, since it uses assemblies from a package.

By the way, thanks for a feedback!

**Comment by ionoy** [comment]
Almost forgot. You need to import `MahApps.Metro.Controls` not `MahApps.Metro`, because `MetroWindow` resides in `Controls`.

**Comment by spowner** [comment]
right. It was just a typo ^^;  Thank you for taking care of it!
