### ISSUE TITLE
Demo of how to do conditionals needed

### ISSUE THREAD

**Issue by paul-hammant** [AmmyUI/AmmyUI#66]
Here's an example in QML - http://paulhammant.com/2015/08/12/making-a-very-small-mp3-player-with-qml/

A little inline determination as to what to show for playing/versus not playing, and association click actions.

**Comment by ionoy** [comment]
Hello Paul,

Conditions on XAML platforms are usually implemented via binding. Ammy doesn't go against MVVM, it just makes working with it easier. QML has a notion of `property` which doesn't exist in XAML, that's why you can't translate your example directly.

Proper way of doing it in XAML/MVVM is creating a ViewModel such as:

```
public bool IsPlaying { get; set; }
public ICommand Play { get; }
public ICommand Stop { get; }
```

And view:

```
Button {
  Content: bind IsPlaying 
           convert (bool playing) => playing ? "Stop music" : "Start music"

  Command: bind // Leave Path empty to bind the whole ViewModel
           convert (ViewModel vm) => vm.IsPlaying ? vm.Stop : vm.Play
}
```

Or you can create two buttons and show/hide them based on `IsPlaying` value. I'd actually prefer two buttons because it would make it easier to add features.

**Comment by ionoy** [comment]
You can also create a `Condition` mixin that applies triggers:

```
mixin Condition(property, value, setProperty, setValue) for FrameworkElement {
    Style: combine Style {
        TargetType: FrameworkElement

        Triggers: [
            DataTrigger {
                Property: $property
                Value: $value

                Setter {
                    Property: $setProperty
                    Value: $setValue
                }
            }
        ]
    }
}

Button {
    #Condition("IsPlaying", true, "Content", "Stop playing")
    #Condition("IsPlaying", true, "Command", bind Stop)

    Content: "Start playing"
    Command: bind Play
}
```

**Comment by paul-hammant** [comment]
Thanks for the quick response :)
